version: '3.7'

services:
  nodejs:
    build: 
      context: .
    image: megabeehothanhminh/nodejs-mysql-app
    networks:
      - nodejs
    environment:
      - MYSQL_PORT=3030
      - MYSQL_HOST=myspa-mysql
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DB=myspa_checkin
    ports:
      - "4200:4200"
    container_name: nodejs-mysql-app
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    networks:
      - nodejs
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=myspa_checkin
    container_name: myspa-mysql
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:4.7
  #   depends_on:
  #     - mysql
  #   networks:
  #     - nodejs
  #   ports:
  #     - "3030:80"
  #   environment:
  #     - PMA_HOST=myspa-mysql
  #     - PMA_PORT=3306
  #   volumes:
  #     - /sessions
  #   container_name: myspa-phpmyadmin-app
volumes:
  mysql:
  phpmyadmin_data:

networks:
  nodejs: